version: "3.8"

services:
  nuxt:
    build: ./infra/node
    ports:
      - "8099:8099"
    container_name: nuxt
    volumes:
      - ./nuxt:/app
      - /app/node_modules
    command: sh -c "yarn && yarn dev"
    tty: true


  web:
    image: nginx
    ports:
      - "8003:85"
    container_name: nginx
    hostname: web-server
    volumes:
      - ./infra/nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./laravel/public:/var/www/project/public
    restart: always

  php:
    ports:
      - "85:85"
    build: ./infra/php
    container_name: laravel
    volumes:
      - ./laravel:/var/www/project
    working_dir: /var/www/project
    env_file:
      - ./laravel/.env

  composer:
    build: ./infra/composer
    command: >
      bash -c "composer install && bash"
    tty: true
    container_name: composer
    volumes:
      - ./laravel:/app


  db_local:
    image: mysql:8.0
    container_name: db
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: sample
      MYSQL_USER: sample
      MYSQL_PASSWORD: sample
      TZ: "Asia/Tokyo"

    command: --default-authentication-plugin=mysql_native_password
    volumes:
      - ./infra/db/data:/var/www/mysql
      - ./infra/db/my.conf:/etc/mysql/conf.d/my.cnf
    ports:
      - 3306:3306
